// Animated figures. Each one replaces the static fallback inside a
// <div class="viz" data-viz="..."> and only runs while it is on screen.
// Data comes from data.js (generated by figures/build.py).
(function () {
  const DATA = window.SITE_DATA;
  if (!DATA) return;
  const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const NS = "http://www.w3.org/2000/svg";
  document.documentElement.classList.add("js");

  function svgEl(parent, name, attrs, text) {
    const node = document.createElementNS(NS, name);
    for (const k in attrs) node.setAttribute(k, attrs[k]);
    if (text != null) node.textContent = text;
    if (parent) parent.appendChild(node);
    return node;
  }
  function html(tag, attrs, ...kids) {
    const node = document.createElement(tag);
    for (const k in attrs || {}) {
      if (k === "class") node.className = attrs[k];
      else if (k === "text") node.textContent = attrs[k];
      else node.setAttribute(k, attrs[k]);
    }
    kids.forEach((kid) => kid && node.append(kid));
    return node;
  }

  // Calls onChange(true) while the element is on screen and the viewer hasn't
  // paused it. Returns a play/pause toggle wired to an optional button.
  function playable(root, onChange, button, labels) {
    let visible = false, wanted = !reduce;
    const sync = () => {
      onChange(visible && wanted);
      if (button) button.textContent = wanted ? labels[1] : labels[0];
    };
    new IntersectionObserver((entries) => { visible = entries[0].isIntersecting; sync(); }, { threshold: 0.15 }).observe(root);
    if (button) button.addEventListener("click", () => { wanted = !wanted; sync(); });
    sync();
    return { set(v) { wanted = v; sync(); }, get on() { return wanted; } };
  }

  function mount(name, fn) {
    document.querySelectorAll(`.viz[data-viz="${name}"]`).forEach((root) => {
      try { root.replaceChildren(); root.classList.add("viz-live"); fn(root); }
      catch (err) { console.error(name, err); }
    });
  }

  // ---------------------------------------------------------------- the debate
  mount("debate", (root) => {
    const { agents, messages, topic } = DATA.debate;
    const pos = [[180, 118], [58, 42], [302, 42], [180, 206]]; // regulator in the middle
    const lastRound = messages[messages.length - 1][0];

    root.append(html("p", { class: "viz-explain", text: `Four AI chatbots argue: “${topic}” Every message is scored from −1 (disagrees with what it answers) to +1 (agrees). Watch who ends up talking to whom.` }));
    const svg = svgEl(null, "svg", { class: "debate-svg", viewBox: "0 0 360 252", role: "img", "aria-label": "Replay of the debate: messages travel between the four agents" });
    root.append(svg);
    const log = html("pre", { class: "term-log", "aria-live": "off" });
    root.append(log);
    const btn = html("button", { class: "viz-btn", type: "button" });
    const again = html("button", { class: "viz-btn", type: "button", text: "[ RESTART ]" });
    const counter = html("span", { class: "viz-read" });
    root.append(html("div", { class: "viz-bar" }, btn, again, counter));
    root.append(html("p", { class: "viz-key" },
      html("span", { class: "k-agree", text: "● agrees" }), html("span", { class: "k-neutral", text: "● neutral" }), html("span", { class: "k-dis", text: "✕ disagrees" })));

    // every ordered pair of agents is a possible edge
    const edges = {};
    for (let a = 0; a < 4; a++) for (let b = 0; b < 4; b++) {
      if (a === b) continue;
      const [x1, y1] = pos[a], [x2, y2] = pos[b];
      const dx = x2 - x1, dy = y2 - y1, len = Math.hypot(dx, dy), ux = dx / len, uy = dy / len;
      const sx = x1 + ux * 12, sy = y1 + uy * 12, ex = x2 - ux * 12, ey = y2 - uy * 12;
      const mx = (sx + ex) / 2 - uy * 9, my = (sy + ey) / 2 + ux * 9;
      const path = svgEl(svg, "path", { class: "d-edge", d: `M${sx.toFixed(1)},${sy.toFixed(1)}Q${mx.toFixed(1)},${my.toFixed(1)} ${ex.toFixed(1)},${ey.toFixed(1)}` });
      edges[a + "-" + b] = { path, n: 0, sum: 0, len: path.getTotalLength() };
    }
    const labels = agents.map((name, i) => {
      const [x, y] = pos[i];
      svgEl(svg, "circle", { class: i === 0 ? "d-node hub" : "d-node", cx: x, cy: y, r: 8 });
      const t = svgEl(svg, "text", { class: "d-name", x: i === 0 ? x + 14 : x, y: i === 0 ? y + 5 : (y < 100 ? y - 14 : y + 24), "text-anchor": i === 0 ? "start" : "middle" }, name);
      const c = svgEl(svg, "text", { class: "d-count", x: i === 0 ? x + 14 : x, y: i === 0 ? y + 21 : (y < 100 ? y - 28 : y + 38), "text-anchor": i === 0 ? "start" : "middle" }, "");
      return { t, c, sent: 0, got: 0 };
    });
    const pulses = svgEl(svg, "g", {});

    let i = 0, timer = null, raf = null, live = [];
    const kind = (s) => (s >= 0.33 ? "agree" : s <= -0.33 ? "dis" : "neutral");
    const fmt = (s) => (s >= 0 ? "+" : "−") + Math.abs(s).toFixed(2);

    function land(m) {
      const e = edges[m[1] + "-" + m[2]];
      e.n++; e.sum += m[3];
      const mean = e.sum / e.n;
      e.path.setAttribute("class", "d-edge used " + kind(mean));
      e.path.style.strokeWidth = (1.8 + Math.min(2.4, e.n / 16)).toFixed(2);
      labels[m[1]].sent++; labels[m[2]].got++;
      labels.forEach((l) => { l.c.textContent = l.sent + l.got ? `sent ${l.sent}, got ${l.got}` : ""; });
    }
    function logLine(m) {
      const line = html("span", { class: "log-line " + kind(m[3]) });
      line.textContent = `r${String(m[0]).padStart(2, "0")} ${agents[m[1]]}>${agents[m[2]]}  ${fmt(m[3])}  ${m[4]}`;
      log.append(line);
      while (log.children.length > 3) log.firstChild.remove();
    }
    function readout() {
      const r = i ? messages[Math.min(i, messages.length) - 1][0] : 0;
      counter.textContent = i >= messages.length
        ? `DONE: ${messages.length} MESSAGES, ALL THROUGH THE REGULATOR`
        : `ROUND ${String(r).padStart(2, "0")}/${lastRound}  MSG ${String(i).padStart(3, "0")}/${messages.length}`;
    }
    function send() {
      if (i >= messages.length) { clearInterval(timer); timer = null; setTimeout(() => { if (ctl.on) restart(); }, 6000); return; }
      const m = messages[i++];
      const e = edges[m[1] + "-" + m[2]];
      const k = kind(m[3]);
      const node = k === "dis"
        ? svgEl(pulses, "path", { class: "d-pulse dis", d: "M-4,-4L4,4M-4,4L4,-4" })
        : svgEl(pulses, "circle", { class: "d-pulse " + k, r: 4 });
      live.push({ node, e, m, t0: performance.now() });
      logLine(m);
      readout();
      if (!raf) raf = requestAnimationFrame(frame);
    }
    function frame(now) {
      live = live.filter((p) => {
        const f = (now - p.t0) / 520;
        if (f >= 1) { p.node.remove(); land(p.m); return false; }
        const pt = p.e.path.getPointAtLength(f * p.e.len);
        p.node.setAttribute("transform", `translate(${pt.x.toFixed(1)},${pt.y.toFixed(1)})`);
        return true;
      });
      raf = live.length ? requestAnimationFrame(frame) : null;
    }
    function reset() {
      i = 0; live.forEach((p) => p.node.remove()); live = [];
      Object.values(edges).forEach((e) => { e.n = 0; e.sum = 0; e.path.setAttribute("class", "d-edge"); e.path.style.strokeWidth = ""; });
      labels.forEach((l) => { l.sent = 0; l.got = 0; l.c.textContent = ""; });
      log.replaceChildren(); readout();
    }
    function finish() { // the end state, without animation
      reset(); messages.forEach(land); messages.slice(-3).forEach(logLine); i = messages.length; readout();
    }
    function restart() { reset(); if (ctl.on) run(true); }
    function run(on) {
      clearInterval(timer); timer = null;
      if (on && i < messages.length) timer = setInterval(send, 260);
    }
    again.addEventListener("click", () => { reset(); ctl.set(true); });
    const ctl = playable(root, run, btn, ["[ PLAY ]", "[ PAUSE ]"]);
    if (reduce) finish(); else readout();
  });

  // ---------------------------------------------------------------- the invented language
  mount("words", (root) => {
    const { colors, shapes, sizes, objects, words } = DATA.words;
    const HEX = { red: "#e53935", blue: "#1e63d0", green: "#2e9e44", yellow: "#f2c300", purple: "#8e44ad", orange: "#f57c00", pink: "#ec6fa5", brown: "#7a4a21" };
    const SCALE = [0.38, 0.58, 0.79, 1];
    const index = {};
    objects.forEach((o, k) => { index[o.join(",")] = k; });

    // letters for the byte values the sender actually uses, most frequent first
    const freq = {};
    words.forEach((w) => w.forEach((b) => { freq[b] = (freq[b] || 0) + 1; }));
    const glyphs = "ABCDEFGHIJKLMNOPQRSTUVWXYZΔΣΦΨΩΓΛΞΠΘ".split("");
    const letter = {};
    Object.keys(freq).sort((a, b) => freq[b] - freq[a]).forEach((b, k) => { letter[b] = glyphs[k] || "?"; });

    function shapePath(name, r) {
      const poly = (pts) => "M" + pts.map((p) => p.map((v) => (v * r).toFixed(1)).join(",")).join("L") + "Z";
      const ring = (n, rot, inner) => {
        const pts = [];
        for (let k = 0; k < n * (inner ? 2 : 1); k++) {
          const rad = inner && k % 2 ? inner : 1;
          const a = rot + (Math.PI * 2 * k) / (n * (inner ? 2 : 1));
          pts.push([Math.cos(a) * rad, Math.sin(a) * rad]);
        }
        return poly(pts);
      };
      switch (name) {
        case "circle": return `M${-r},0a${r},${r} 0 1,0 ${2 * r},0a${r},${r} 0 1,0 ${-2 * r},0Z`;
        case "square": return poly([[-0.85, -0.85], [0.85, -0.85], [0.85, 0.85], [-0.85, 0.85]]);
        case "triangle": return ring(3, -Math.PI / 2);
        case "star": return ring(5, -Math.PI / 2, 0.42);
        case "cross": return poly([[-0.3, -1], [0.3, -1], [0.3, -0.3], [1, -0.3], [1, 0.3], [0.3, 0.3], [0.3, 1], [-0.3, 1], [-0.3, 0.3], [-1, 0.3], [-1, -0.3], [-0.3, -0.3]]);
        case "diamond": return poly([[0, -1], [0.7, 0], [0, 1], [-0.7, 0]]);
        case "hexagon": return ring(6, 0);
        default: return poly([[-1, -0.3], [0.2, -0.3], [0.2, -0.8], [1, 0], [0.2, 0.8], [0.2, 0.3], [-1, 0.3]]); // arrow
      }
    }
    function drawObject(o, box) {
      const s = svgEl(null, "svg", { viewBox: `${-box} ${-box} ${box * 2} ${box * 2}`, class: "w-obj", role: "img", "aria-label": `${sizes[o[2]]} ${colors[o[0]]} ${shapes[o[1]]}` });
      svgEl(s, "path", { d: shapePath(shapes[o[1]], box * 0.82 * SCALE[o[2]]), fill: HEX[colors[o[0]]] });
      return s;
    }

    root.append(html("p", { class: "viz-explain", text: "Two neural networks play a guessing game. The sender sees one object and may send only 8 symbols. The receiver must then pick that object out of a line-up of 8. Nobody gave them a language. This is the one they invented." }));
    const pickers = [["Colour", colors], ["Shape", shapes], ["Size", sizes]].map(([name, opts]) => {
      const sel = html("select", { "aria-label": name });
      opts.forEach((o, k) => sel.append(html("option", { value: k, text: o })));
      return sel;
    });
    const surprise = html("button", { class: "win-btn", type: "button", text: "Surprise me" });
    root.append(html("div", { class: "w-pick" },
      html("label", {}, "Colour ", pickers[0]), html("label", {}, "Shape ", pickers[1]), html("label", {}, "Size ", pickers[2]), surprise));
    const objBox = html("div", { class: "w-target" });
    const wordBox = html("div", { class: "w-word", "aria-live": "polite" });
    root.append(html("div", { class: "w-stage" }, objBox, html("div", {}, html("span", { class: "w-says", text: "the sender says:" }), wordBox)));
    const lineup = html("div", { class: "w-lineup" });
    root.append(html("p", { class: "w-label", text: "The receiver has to find it in a line-up like this (the target is ringed):" }), lineup);
    const note = html("p", { class: "viz-note" });
    root.append(note);

    let cur = [0, 3, 3], prevWord = null;
    function show(o, announce) {
      cur = o.slice();
      pickers.forEach((p, k) => { p.value = o[k]; });
      const k = index[o.join(",")];
      const word = words[k];
      objBox.replaceChildren(drawObject(o, 50), html("span", { text: `${sizes[o[2]]} ${colors[o[0]]} ${shapes[o[1]]}` }));
      wordBox.replaceChildren();
      let changed = 0;
      word.forEach((b, pos) => {
        const diff = prevWord && prevWord[pos] !== b;
        if (diff) changed++;
        wordBox.append(html("span", { class: "w-tile" + (diff ? " changed" : ""), text: letter[b] }));
      });
      note.textContent = prevWord && announce
        ? `${changed} of 8 symbols changed. A tidy language would change only the symbols for the feature you changed; this one mixes them (its tidiness score, topographic similarity, is 0.23, where 1 is perfectly tidy), yet the receiver still understands it.`
        : "Letters stand for the 31 byte values the sender actually uses. Change one feature and see which symbols change.";
      prevWord = word;
      // an example line-up: the target and 7 other objects
      let seed = k * 7919 + 13;
      const rnd = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff; };
      const others = new Set();
      while (others.size < 7) { const j = Math.floor(rnd() * objects.length); if (j !== k) others.add(j); }
      const row = [...others]; row.splice(Math.floor(rnd() * 8), 0, k);
      lineup.replaceChildren(...row.map((j) => html("span", { class: j === k ? "w-cand target" : "w-cand" }, drawObject(objects[j], 22))));
    }
    let auto = null, step = 0, touched = false;
    function demo() { // change one feature at a time so the differences are visible
      const o = cur.slice(), which = step++ % 3;
      const n = [colors.length, shapes.length, sizes.length][which];
      o[which] = (o[which] + 1 + Math.floor(Math.random() * (n - 1))) % n;
      show(o, true);
    }
    const stopDemo = () => { touched = true; clearInterval(auto); auto = null; };
    pickers.forEach((p) => p.addEventListener("change", () => { stopDemo(); show(pickers.map((q) => +q.value), true); }));
    surprise.addEventListener("click", () => { stopDemo(); show(objects[Math.floor(Math.random() * objects.length)], true); });
    show(cur, false);
    playable(root, (on) => {
      clearInterval(auto); auto = null;
      if (on && !touched) auto = setInterval(demo, 2600);
    });
  });

  // ---------------------------------------------------------------- the strip chart
  mount("strip", (root) => {
    const T = DATA.traces;
    const W = 360, PH = 86, L = 8, R = 352;
    const span = Math.max(T.moving.seconds, T.sleeping.seconds);
    const x = (sec) => L + (sec / span) * (R - L);
    const AX = [["x", "c1"], ["y", "c2"], ["z", "c3"]];

    root.append(html("p", { class: "viz-explain", text: "A motion sensor records acceleration 50 times a second in three directions. Walking shakes it in a fast rhythm. Sleep is almost flat, except when the sleeper rolls over. The models read one second at a time and say which it is." }));
    const svg = svgEl(null, "svg", { class: "strip-svg", viewBox: `0 0 ${W} 232`, role: "img", "aria-label": "Chart recorder drawing accelerometer traces for a walking recording and a sleeping recording" });
    root.append(svg);
    const defs = svgEl(svg, "defs", {});
    const clip = svgEl(svgEl(defs, "clipPath", { id: "strip-clip" }), "rect", { x: 0, y: 0, width: 0, height: 232 });

    const panels = [["moving", "Walking", 18], ["sleeping", "Sleeping", 130]].map(([key, title, top]) => {
      const d = T[key], mid = top + PH / 2, n = d.x.length;
      svgEl(svg, "rect", { class: "s-paper", x: L, y: top, width: R - L, height: PH });
      for (let g = 1; g < 4; g++) svgEl(svg, "line", { class: "s-grid", x1: L, x2: R, y1: top + (g * PH) / 4, y2: top + (g * PH) / 4 });
      for (let s = 5; s < span; s += 5) svgEl(svg, "line", { class: "s-grid", x1: x(s), x2: x(s), y1: top, y2: top + PH });
      svgEl(svg, "text", { class: "s-title", x: L, y: top - 5 }, title);
      const g = svgEl(svg, "g", { "clip-path": "url(#strip-clip)" });
      AX.forEach(([axis, cls]) => {
        const pts = d[axis].map((v, i) => `${x((i / (n - 1)) * d.seconds).toFixed(1)},${(mid - v * 34).toFixed(1)}`).join(" ");
        svgEl(g, "polyline", { class: "s-line " + cls, points: pts });
      });
      const win = svgEl(svg, "rect", { class: "s-window", y: top, height: PH, width: x(1) - x(0) });
      return { d, win };
    });
    const pen = svgEl(svg, "line", { class: "s-pen", y1: 12, y2: 222 });
    svgEl(svg, "text", { class: "s-tick", x: L, y: 229 }, "0 s");
    svgEl(svg, "text", { class: "s-tick", x: R, y: 229, "text-anchor": "end" }, `${Math.round(span)} s`);

    const btn = html("button", { class: "viz-btn", type: "button" });
    root.append(html("div", { class: "viz-bar" }, btn,
      html("span", { class: "s-key" }, html("i", { class: "c1" }), "side to side ", html("i", { class: "c2" }), "front to back ", html("i", { class: "c3" }), "up and down "),
      html("span", { class: "s-key" }, html("i", { class: "win" }), "the 1 second the model reads")));

    const meters = html("div", { class: "s-meters" });
    [["Best classical model (kNN)", 93], ["Best deep model (1D CNN)", 82], ["Always guessing “sleeping”", 59]].forEach(([name, v]) => {
      meters.append(html("div", { class: "s-meter" }, html("span", { text: name }), html("b", { text: v + "%" }), html("i", {}, html("u", { style: `--v:${v}%` }))));
    });
    root.append(html("p", { class: "w-label", text: "How often each gets a window right, on recordings it never saw:" }), meters);

    let sec = 0, raf = null, last = 0;
    function place() {
      clip.setAttribute("width", x(sec));
      pen.setAttribute("x1", x(sec)); pen.setAttribute("x2", x(sec));
      panels.forEach((p) => {
        const s = Math.min(sec, p.d.seconds);
        p.win.setAttribute("x", Math.max(L, x(s) - (x(1) - x(0))));
      });
    }
    function frame(now) {
      sec += ((now - last) / 1000) * 3; last = now; // three times real speed
      if (sec > span + 1.5) sec = 0;
      place();
      raf = requestAnimationFrame(frame);
    }
    playable(root, (on) => {
      cancelAnimationFrame(raf); raf = null;
      if (on) { last = performance.now(); raf = requestAnimationFrame(frame); }
    }, btn, ["Run the recorder", "Pause"]);
    if (reduce) { sec = span; place(); }
  });

  // ---------------------------------------------------------------- the price tape
  mount("ticker", (root) => {
    const prices = DATA.market.prices, n = prices.length;
    const W = 360, H = 190, L = 30, R = 318, T = 12, B = 166;
    const lo = 10, hi = 25;
    const x = (i) => L + (i / (n - 1)) * (R - L), y = (p) => T + ((hi - p) / (hi - lo)) * (B - T);

    root.append(html("p", { class: "viz-explain", text: "202 robot traders, each following its own rule, buy and sell one made-up stock. Nobody sets the price: it is simply what the latest trades went for. These are 300 rounds of trading." }));
    const read = html("p", { class: "viz-read tick-read", "aria-live": "off" });
    root.append(read);
    const svg = svgEl(null, "svg", { class: "tick-svg", viewBox: `0 0 ${W} ${H}`, role: "img", "aria-label": "The stock price drawn round by round" });
    root.append(svg);
    [10, 15, 20, 25].forEach((v) => {
      svgEl(svg, "line", { class: "t-grid", x1: L, x2: R, y1: y(v), y2: y(v) });
      svgEl(svg, "text", { class: "t-axis", x: L - 6, y: y(v) + 5, "text-anchor": "end" }, v);
    });
    [0, 100, 200, 300].forEach((v) => svgEl(svg, "text", { class: "t-axis", x: x(Math.min(v, n - 1)), y: H - 6, "text-anchor": "middle" }, v));
    const ghost = svgEl(svg, "path", { class: "t-ghost", d: "M" + prices.map((p, i) => `${x(i).toFixed(1)},${y(p).toFixed(1)}`).join("L") });
    const line = svgEl(svg, "path", { class: "t-line" });
    const head = svgEl(svg, "circle", { class: "t-head", r: 4 });
    const tag = svgEl(svg, "text", { class: "t-tag" });

    const btn = html("button", { class: "viz-btn", type: "button" });
    const scrub = html("input", { type: "range", min: 0, max: n - 1, value: 0, "aria-label": "Round of trading" });
    root.append(html("div", { class: "viz-bar" }, btn, scrub));
    root.append(html("p", { class: "viz-note", text: "THE TRADERS: 160 WRITTEN IN C++ (100 RANDOM, 20 SMART, 20 MARKET-ORDER, 20 LIMIT-ORDER) AND 42 IN PYTHON (30 RANDOM, 10 MOVING-AVERAGE, 2 LSTM NEURAL NETWORKS)." }));

    let i = 0, timer = null;
    function place() {
      let d = "";
      for (let k = 0; k <= i; k++) d += (k ? "L" : "M") + x(k).toFixed(1) + "," + y(prices[k]).toFixed(1);
      line.setAttribute("d", d);
      head.setAttribute("cx", x(i)); head.setAttribute("cy", y(prices[i]));
      tag.setAttribute("x", Math.min(x(i) + 8, W - 2)); tag.setAttribute("y", y(prices[i]) + 5);
      tag.textContent = prices[i].toFixed(1);
      const ch = i ? prices[i] - prices[i - 1] : 0;
      const seen = prices.slice(0, i + 1);
      read.textContent = `ROUND ${String(i).padStart(3, "0")}  PRICE ${prices[i].toFixed(2)}  ${ch >= 0 ? "▲" : "▼"} ${Math.abs(ch).toFixed(2)}  HIGH ${Math.max(...seen).toFixed(1)}  LOW ${Math.min(...seen).toFixed(1)}`;
      scrub.value = i;
    }
    function tick() { i = i >= n - 1 ? 0 : i + 1; place(); }
    const ctl = playable(root, (on) => { clearInterval(timer); timer = null; if (on) timer = setInterval(tick, 70); }, btn, ["[ PLAY ]", "[ PAUSE ]"]);
    scrub.addEventListener("input", () => { ctl.set(false); i = +scrub.value; place(); });
    if (reduce) i = n - 1;
    ghost.style.display = reduce ? "none" : "";
    place();
  });

  // ---------------------------------------------------------------- particle life
  // A browser port of the rules in Particle_Simulator/Clusters/clusters.c:
  // random attraction or repulsion per pair of types with a Gaussian profile,
  // push-apart on overlap, friction, a wrap-around world and a 50 px grid.
  mount("particles", (root) => {
    const SIZE = 700, TYPES = 8, PER = 100, N = TYPES * PER, CELL = 50, COLS = SIZE / CELL;
    const MIN_D = 3, MAX_D = 50, FRICTION = 0.8, GRAVITY = 0.05, MAX_SPEED = 60;
    const COLORS = ["#5577ff", "#ff5555", "#55ff55", "#ffff55", "#ff55ff", "#55ffff", "#ffffff", "#ffaa00"];

    root.append(html("p", { class: "viz-explain", text: "Each dot has one of 8 colours. Every pair of colours either attracts or repels, by rules picked at random. That is the whole program, yet the dots gather into clusters that drift around like living cells. Press New rules for a different world." }));
    const canvas = html("canvas", { width: SIZE, height: SIZE, class: "p-canvas", role: "img", "aria-label": "Live particle simulation: 800 coloured dots forming clusters" });
    root.append(html("div", { class: "win-sunken p-screen" }, canvas));
    const btn = html("button", { class: "win-btn", type: "button" });
    const fresh = html("button", { class: "win-btn", type: "button", text: "New rules" });
    root.append(html("div", { class: "viz-bar" }, fresh, btn));
    root.append(html("p", { class: "viz-note", text: "Running live in your browser with the simulator's rules. The original is written in C and splits the work across CPU cores with OpenMP." }));
    const ctx = canvas.getContext("2d");

    const px = new Float32Array(N), py = new Float32Array(N), vx = new Float32Array(N), vy = new Float32Array(N);
    const sx = new Float32Array(N), sy = new Float32Array(N), type = new Uint8Array(N);
    const force = new Float32Array(TYPES * TYPES), reach = new Float32Array(TYPES * TYPES);
    const cellStart = new Int32Array(COLS * COLS + 1), cellOf = new Int32Array(N), order = new Int32Array(N);

    function rules() {
      for (let k = 0; k < TYPES * TYPES; k++) {
        force[k] = Math.random() * 2 - 1;                                   // MIN_FORCE..MAX_FORCE
        reach[k] = MIN_D + Math.floor(Math.random() * (MAX_D - MIN_D + 1)); // MIN_COL_DIST..MAX_COL_DIST
      }
    }
    function scatter() {
      for (let i = 0; i < N; i++) { px[i] = Math.random() * SIZE; py[i] = Math.random() * SIZE; vx[i] = vy[i] = 0; type[i] = Math.floor(i / PER); }
    }
    function step() {
      // counting sort into grid cells, as assign_balls_to_grid does
      cellStart.fill(0);
      for (let i = 0; i < N; i++) {
        const c = (Math.floor(py[i] / CELL) % COLS + COLS) % COLS * COLS + (Math.floor(px[i] / CELL) % COLS + COLS) % COLS;
        cellOf[i] = c; cellStart[c + 1]++;
      }
      for (let c = 0; c < COLS * COLS; c++) cellStart[c + 1] += cellStart[c];
      const fill = cellStart.slice(0, COLS * COLS);
      for (let i = 0; i < N; i++) order[fill[cellOf[i]]++] = i;
      sx.set(px); sy.set(py); // forces read the positions from the start of the frame

      for (let i = 0; i < N; i++) {
        const ci = cellOf[i], row = Math.floor(ci / COLS), col = ci % COLS, ti = type[i] * TYPES;
        for (let dr = -1; dr <= 1; dr++) for (let dc = -1; dc <= 1; dc++) {
          const c = ((row + dr + COLS) % COLS) * COLS + ((col + dc + COLS) % COLS);
          for (let q = cellStart[c]; q < cellStart[c + 1]; q++) {
            const j = order[q];
            if (j === i) continue;
            let dx = sx[j] - px[i], dy = sy[j] - py[i];
            if (dx > SIZE / 2) dx -= SIZE; else if (dx < -SIZE / 2) dx += SIZE;
            if (dy > SIZE / 2) dy -= SIZE; else if (dy < -SIZE / 2) dy += SIZE;
            const d2 = dx * dx + dy * dy;
            if (d2 < 1e-6) continue;
            const max = reach[ti + type[j]];
            if (d2 > max * max) continue;
            const d = Math.sqrt(d2);
            if (d < 2 * MIN_D) { // overlapping: push this one away
              const overlap = (2 * MIN_D - d) / 2;
              px[i] -= dx * (overlap / d); py[i] -= dy * (overlap / d);
              if (px[i] < 0) px[i] += SIZE; else if (px[i] >= SIZE) px[i] -= SIZE;
              if (py[i] < 0) py[i] += SIZE; else if (py[i] >= SIZE) py[i] -= SIZE;
            }
            if (d < MIN_D) continue;
            const ideal = max / 2, sigma = ideal / 3;
            const f = force[ti + type[j]] * Math.exp(-((d - ideal) * (d - ideal)) / (2 * sigma * sigma));
            vx[i] += (dx / d) * f; vy[i] += (dy / d) * f;
          }
        }
      }
      for (let i = 0; i < N; i++) {
        vx[i] *= FRICTION; vy[i] *= FRICTION; py[i] += GRAVITY;
        const s2 = vx[i] * vx[i] + vy[i] * vy[i];
        if (s2 > MAX_SPEED * MAX_SPEED) { const s = Math.sqrt(s2); vx[i] = (vx[i] / s) * MAX_SPEED; vy[i] = (vy[i] / s) * MAX_SPEED; }
        px[i] += vx[i]; py[i] += vy[i];
        if (px[i] >= SIZE) px[i] -= SIZE; else if (px[i] < 0) px[i] += SIZE;
        if (py[i] >= SIZE) py[i] -= SIZE; else if (py[i] < 0) py[i] += SIZE;
      }
    }
    function draw() {
      ctx.fillStyle = "#000"; ctx.fillRect(0, 0, SIZE, SIZE);
      for (let t = 0; t < TYPES; t++) {
        ctx.fillStyle = COLORS[t];
        for (let i = t * PER; i < (t + 1) * PER; i++) ctx.fillRect(px[i] - 2.5, py[i] - 2.5, 5, 5);
      }
    }
    let raf = null, last = 0;
    function frame(now) {
      if (now - last >= 33) { last = now; step(); draw(); } // the original runs at 30 frames a second
      raf = requestAnimationFrame(frame);
    }
    rules(); scatter();
    for (let k = 0; k < (reduce ? 300 : 40); k++) step();
    draw();
    fresh.addEventListener("click", () => { rules(); scatter(); draw(); });
    playable(root, (on) => { cancelAnimationFrame(raf); raf = null; if (on) raf = requestAnimationFrame(frame); }, btn, ["Play", "Pause"]);
  });

  // ---------------------------------------------------------------- SVD slider
  mount("svd", (root) => {
    const ranks = DATA.svd.ranks;
    root.append(html("p", { class: "viz-explain", text: "A picture is a grid of numbers. SVD sorts the picture's patterns from most to least important. Keep only the top few and you can rebuild it from a fraction of the data. Drag the slider." }));
    const img = html("img", { class: "svd-img", width: 480, height: 271, alt: "" });
    root.append(img);
    const slider = html("input", { type: "range", min: 0, max: ranks.length - 1, value: 0, "aria-label": "How many patterns to keep" });
    const read = html("p", { class: "svd-read", "aria-live": "polite" });
    root.append(html("div", { class: "svd-ctl" }, html("span", { text: "less data" }), slider, html("span", { text: "more data" })), read);
    ranks.forEach((r) => { new Image().src = `img/svd-${r.rank}.webp`; });
    function show(k) {
      const r = ranks[k];
      slider.value = k;
      img.src = `img/svd-${r.rank}.webp`;
      img.alt = `The image rebuilt from its top ${r.rank} patterns`;
      const pct = r.share * 100;
      read.replaceChildren(html("b", { text: r.rank === 1 ? "1 pattern" : `${r.rank} patterns` }),
        r.share >= 1 ? " kept: the original image, every number." : ` kept: rebuilt from ${pct < 10 ? pct.toFixed(1) : Math.round(pct)}% of the numbers.`);
    }
    let auto = null, k = 0, touched = false;
    slider.addEventListener("input", () => { touched = true; clearInterval(auto); auto = null; show(+slider.value); });
    show(reduce ? 8 : 0);
    playable(root, (on) => {
      clearInterval(auto); auto = null;
      if (on && !touched) auto = setInterval(() => { k = (k + 1) % ranks.length; show(k); }, 900);
    });
  });

  // ---------------------------------------------------------------- page-level life
  // Windows open in their era's way the first time they scroll into view.
  if (!reduce) {
    const opener = new IntersectionObserver((entries) => {
      entries.forEach((e) => { if (e.isIntersecting) { e.target.classList.add("open"); opener.unobserve(e.target); } });
    }, { threshold: 0.08 });
    document.querySelectorAll(".mac, .term, .win, .manual").forEach((w) => { w.classList.add("pre"); opener.observe(w); });
  }
  const clock = document.getElementById("clock");
  if (clock) {
    const tick = () => { clock.textContent = new Date().toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); };
    tick(); setInterval(tick, 20000);
  }
})();
