// Animated figures. Each one replaces the static fallback inside a
// <div class="viz" data-viz="..."> and only runs while it is on screen.
// Data comes from data.js (generated by figures/build.py).
(function () {
  const DATA = window.SITE_DATA;
  if (!DATA) return;
  const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const NS = "http://www.w3.org/2000/svg";
  document.documentElement.classList.add("js");

  function svgEl(parent, name, attrs, text) {
    const node = document.createElementNS(NS, name);
    for (const k in attrs) node.setAttribute(k, attrs[k]);
    if (text != null) node.textContent = text;
    if (parent) parent.appendChild(node);
    return node;
  }
  function html(tag, attrs, ...kids) {
    const node = document.createElement(tag);
    for (const k in attrs || {}) {
      if (k === "class") node.className = attrs[k];
      else if (k === "text") node.textContent = attrs[k];
      else node.setAttribute(k, attrs[k]);
    }
    kids.forEach((kid) => kid && node.append(kid));
    return node;
  }

  // Calls onChange(true) while the element is on screen and the viewer hasn't
  // paused it. Returns a play/pause toggle wired to an optional button.
  function playable(root, onChange, button, labels) {
    let visible = false, wanted = !reduce;
    const sync = () => {
      onChange(visible && wanted);
      if (button) button.textContent = wanted ? labels[1] : labels[0];
    };
    new IntersectionObserver((entries) => { visible = entries[0].isIntersecting; sync(); }, { threshold: 0.15 }).observe(root);
    if (button) button.addEventListener("click", () => { wanted = !wanted; sync(); });
    sync();
    return { set(v) { wanted = v; sync(); }, get on() { return wanted; } };
  }

  function mount(name, fn) {
    document.querySelectorAll(`.viz[data-viz="${name}"]`).forEach((root) => {
      try { root.replaceChildren(); root.classList.add("viz-live"); fn(root); }
      catch (err) { console.error(name, err); }
    });
  }

  // ---------------------------------------------------------------- LLM agent conversations
  // One 4-agent debate and five 3-agent "triad" experiments, replayed from the logs.
  mount("debate", (root) => {
    const exps = DATA.debate.experiments;
    const pick = html("select", { "aria-label": "Experiment" });
    exps.forEach((e, k) => pick.append(html("option", { value: k, text: e.title })));
    root.append(html("label", { class: "viz-pick" }, "EXPERIMENT ", pick));
    const explain = html("p", { class: "viz-explain" });
    root.append(explain);
    const svg = svgEl(null, "svg", { class: "debate-svg", viewBox: "0 0 360 300", role: "img", "aria-label": "Replay of the conversation: messages travel between the agents" });
    root.append(svg);
    const log = html("pre", { class: "term-log", "aria-live": "off" });
    root.append(log);
    const btn = html("button", { class: "viz-btn", type: "button" });
    const again = html("button", { class: "viz-btn", type: "button", text: "[ RESTART ]" });
    const counter = html("span", { class: "viz-read" });
    root.append(html("div", { class: "viz-bar" }, btn, again, counter));
    const keyGood = html("span", { class: "k-agree" }), keyBad = html("span", { class: "k-dis" });
    root.append(html("p", { class: "viz-key" }, keyGood, html("span", { class: "k-neutral", text: "● neutral" }), keyBad));
    const note = html("p", { class: "viz-note" });
    root.append(note);

    let E, edges, labels, pairs, pulses, ticks, cut, i = 0, timer = null, raf = null, live = [];
    const kind = (s) => (s >= cut ? "agree" : s <= -cut ? "dis" : "neutral");
    const fmt = (s) => (s >= 0 ? "+" : "−") + Math.abs(s).toFixed(2);
    const pairKey = (a, b) => Math.min(a, b) + "-" + Math.max(a, b);

    function setup(k) {
      clearInterval(timer); timer = null; cancelAnimationFrame(raf); raf = null; live = [];
      E = exps[k];
      const triad = E.agents.length === 3;
      cut = E.scorer === "NLI" ? 0.33 : 0.1; // TextBlob polarity runs much closer to zero
      const pos = triad ? [[180, 48], [100, 190], [260, 190]] : [[180, 118], [58, 42], [302, 42], [180, 206]];
      const cx = pos.reduce((s, p) => s + p[0], 0) / pos.length, cy = pos.reduce((s, p) => s + p[1], 0) / pos.length;
      explain.textContent = triad
        ? `Balance theory says “my friend’s enemy is my enemy”. Three chatbots are told who their friends and enemies are (${E.kind === "balanced" ? "two allies against one outsider, a stable set-up" : "one is friends with two who dislike each other, a tense set-up"}), then discuss: “${E.topic}” Each message’s tone is scored from −1 (hostile) to +1 (friendly).`
        : `Four AI chatbots with opposed views argue: “${E.topic}” Each opens with one message to a randomly drawn partner, and from then on everyone only replies to whoever wrote to them. Here all three critics drew the regulator, so every exchange runs through it. Each reply is scored from −1 (disagrees with what it answers) to +1 (agrees). Watch the disagreement fade.`;
      keyGood.textContent = triad ? "● friendly" : "● agrees";
      keyBad.textContent = triad ? "✕ hostile" : "✕ disagrees";
      note.textContent = !triad
        ? "What the log shows: the critics start out arguing and end up repeating the regulator. By round 60 all three send it the same sentence. A high score means a reply restates the message it answers, which is not always the same as being persuaded."
        : "What the experiments found: scores drift mildly positive even between pairs told to be enemies. Partly the chatbots smooth things over, and partly the simple tone scorer misses sarcasm, as some log lines show.";
      headline(triad);

      svg.replaceChildren();
      edges = {};
      const n = E.agents.length;
      for (let a = 0; a < n; a++) for (let b = 0; b < n; b++) {
        if (a === b) continue;
        const [x1, y1] = pos[a], [x2, y2] = pos[b];
        const dx = x2 - x1, dy = y2 - y1, len = Math.hypot(dx, dy), ux = dx / len, uy = dy / len;
        const sx = x1 + ux * 12, sy = y1 + uy * 12, ex = x2 - ux * 12, ey = y2 - uy * 12;
        const mx = (sx + ex) / 2 - uy * 9, my = (sy + ey) / 2 + ux * 9;
        const path = svgEl(svg, "path", { class: "d-edge", d: `M${sx.toFixed(1)},${sy.toFixed(1)}Q${mx.toFixed(1)},${my.toFixed(1)} ${ex.toFixed(1)},${ey.toFixed(1)}` });
        edges[a + "-" + b] = { path, n: 0, sum: 0, len: path.getTotalLength() };
      }
      // in the triads, each pair shows what it was told to be and its tone so far
      pairs = {};
      E.seeded.forEach(([a, b, sign]) => {
        const mx = (pos[a][0] + pos[b][0]) / 2, my = (pos[a][1] + pos[b][1]) / 2;
        const ox = mx - cx, oy = my - cy, ol = Math.hypot(ox, oy) || 1;
        // side edges get their label outside the triangle; the bottom edge below it
        const side = Math.abs(ox) > 5;
        const anchor = !side ? "middle" : ox < 0 ? "end" : "start";
        const x = side ? mx + Math.sign(ox) * 14 : mx, y = side ? my - 4 : my + 24;
        svgEl(svg, "text", { class: "d-told", x, y, "text-anchor": anchor }, sign > 0 ? "told: friends" : "told: enemies");
        const tone = svgEl(svg, "text", { class: "d-count", x, y: y + 15, "text-anchor": anchor }, "");
        pairs[pairKey(a, b)] = { sign, tone, n: 0, sum: 0 };
      });
      labels = E.agents.map((name, k2) => {
        const [x, y] = pos[k2];
        const hub = !triad && k2 === 0, top = y < 100;
        svgEl(svg, "circle", { class: hub ? "d-node hub" : "d-node", cx: x, cy: y, r: 8 });
        svgEl(svg, "text", { class: "d-name", x: hub ? x + 14 : x, y: hub ? y + 5 : (top ? y - 14 : y + 24), "text-anchor": hub ? "start" : "middle" }, name);
        const c = triad ? null : svgEl(svg, "text", { class: "d-count", x: hub ? x + 14 : x, y: hub ? y + 21 : (top ? y - 28 : y + 38), "text-anchor": hub ? "start" : "middle" }, "");
        return { c, sent: 0, got: 0 };
      });
      // one tick per reply, in order, so the drift in tone is visible at a glance
      const lastRound = E.messages[E.messages.length - 1][0], colW = 340 / (lastRound + 1), tw = Math.min(12, colW - 0.8);
      svgEl(svg, "text", { class: "d-count", x: 10, y: 262 }, "EVERY REPLY, IN ORDER:");
      svgEl(svg, "text", { class: "d-count", x: 10, y: 298 }, "round 0");
      svgEl(svg, "text", { class: "d-count", x: 350, y: 298, "text-anchor": "end" }, "round " + lastRound);
      const slot = {};
      ticks = E.messages.map((m) => {
        const k2 = slot[m[0]] = (slot[m[0]] || 0) + 1;
        return svgEl(svg, "rect", { class: "d-tick", x: 10 + m[0] * colW + (colW - tw) / 2, y: 262 + k2 * 6, width: tw, height: 5 });
      });
      pulses = svgEl(svg, "g", {});
      reset();
    }

    // The headline number beside the figure follows the experiment being shown.
    const card = root.closest("article");
    const head = card && { amount: card.querySelector(".amount"), what: card.querySelector(".what"), from: card.querySelector(".from") };
    function headline(triad) {
      if (!head || !head.amount || !head.what || !head.from) return;
      const M = E.messages;
      let big, small, what, from;
      if (!triad) {
        const agree = (a, b) => {
          const v = M.filter((m) => m[0] >= a && m[0] <= b);
          return Math.round((100 * v.filter((m) => kind(m[3]) === "agree").length) / v.length);
        };
        big = agree(1, 10) + "%"; small = "TO " + agree(31, 60) + "%";
        what = "of replies scored as agreeing with the message they answer, in rounds 1\u201310 versus rounds 31\u201360 of the debate. The libertarian opens with \u201cGlobal regulation of AI would stifle innovation\u201d and by round 60 writes \u201cExactly; without enforceable global treaties\u2026\u201d";
        from = `the debate\u2019s ${M.length}-message log, scored by an NLI model. A high score means a reply restates what it answers`;
      } else {
        const sign = {};
        E.seeded.forEach(([a, b, sg]) => { sign[pairKey(a, b)] = sg; });
        const mean = (sg) => { const v = M.filter((m) => sign[pairKey(m[1], m[2])] === sg); return v.reduce((t, m) => t + m[3], 0) / v.length; };
        const enemies = E.seeded.filter((p) => p[2] < 0).length, friends = E.seeded.length - enemies;
        const foe = mean(-1), pal = mean(1);
        big = fmt(foe); small = "VS " + fmt(pal);
        what = `average tone between the ${enemies > 1 ? "pairs" : "pair"} told to be enemies, against ${fmt(pal)} between the ${friends > 1 ? "pairs" : "pair"} told to be friends, as three chatbots discuss \u201c${E.topic}\u201d On a scale from \u22121 (hostile) to +1 (friendly)${foe > 0 ? ", even the enemies come out mildly positive" : ", the enemies come out negative"}.`;
        from = `this run\u2019s ${M.length}-message log, scored for tone with TextBlob, which misses sarcasm`;
      }
      head.amount.replaceChildren(big + " ", html("small", { text: small }));
      head.what.textContent = what;
      head.from.replaceChildren(html("span", { text: "computed from" }), " " + from);
    }

    function land(m) {
      const e = edges[m[1] + "-" + m[2]];
      e.n++; e.sum += m[3];
      e.path.setAttribute("class", "d-edge used " + kind(e.sum / e.n));
      e.path.style.strokeWidth = (1.8 + Math.min(2.4, e.n / 16)).toFixed(2);
      labels[m[1]].sent++; labels[m[2]].got++;
      labels.forEach((l) => { if (l.c) l.c.textContent = l.sent + l.got ? `sent ${l.sent}, got ${l.got}` : ""; });
      const p = pairs[pairKey(m[1], m[2])];
      if (p) { p.n++; p.sum += m[3]; p.tone.textContent = "tone so far " + fmt(p.sum / p.n); }
    }
    function mark(idx) { ticks[idx].setAttribute("class", "d-tick " + kind(E.messages[idx][3])); }
    function logLine(m) {
      const line = html("span", { class: "log-line " + kind(m[3]) });
      line.textContent = `r${String(m[0]).padStart(2, "0")} ${E.agents[m[1]]}>${E.agents[m[2]]}  ${fmt(m[3])}  ${m[4]}`;
      log.append(line);
      while (log.children.length > 3) log.firstChild.remove();
    }
    function summary() {
      if (!E.seeded.length) {
        const agree = (a, b) => {
          const v = E.messages.filter((m) => m[0] >= a && m[0] <= b);
          return Math.round((100 * v.filter((m) => kind(m[3]) === "agree").length) / v.length);
        };
        return `DONE: REPLIES SCORED AS AGREEING ROSE FROM ${agree(1, 10)}% (ROUNDS 1-10) TO ${agree(31, 60)}% (ROUNDS 31-60)`;
      }
      const mean = (sign) => {
        const v = Object.values(pairs).filter((p) => p.sign === sign);
        return v.reduce((s, p) => s + p.sum, 0) / Math.max(1, v.reduce((s, p) => s + p.n, 0));
      };
      return `DONE: TOLD-TO-BE ENEMIES AVERAGED ${fmt(mean(-1))}, FRIENDS ${fmt(mean(1))}`;
    }
    function readout() {
      const M = E.messages, last = M[M.length - 1][0];
      const r = i ? M[Math.min(i, M.length) - 1][0] : 0;
      counter.textContent = i >= M.length && !live.length ? summary()
        : `ROUND ${String(r).padStart(2, "0")}/${last}  MSG ${String(Math.min(i, M.length)).padStart(3, "0")}/${M.length}`;
    }
    function send() {
      const M = E.messages;
      if (i >= M.length) { clearInterval(timer); timer = null; setTimeout(() => { if (ctl.on && i >= M.length) restart(); }, 7000); return; }
      mark(i);
      const m = M[i++], e = edges[m[1] + "-" + m[2]], k = kind(m[3]);
      const node = k === "dis"
        ? svgEl(pulses, "path", { class: "d-pulse dis", d: "M-4,-4L4,4M-4,4L4,-4" })
        : svgEl(pulses, "circle", { class: "d-pulse " + k, r: 4 });
      live.push({ node, e, m, t0: performance.now() });
      logLine(m); readout();
      if (!raf) raf = requestAnimationFrame(frame);
    }
    function frame(now) {
      live = live.filter((p) => {
        const f = (now - p.t0) / 520;
        if (f >= 1) { p.node.remove(); land(p.m); return false; }
        const pt = p.e.path.getPointAtLength(f * p.e.len);
        p.node.setAttribute("transform", `translate(${pt.x.toFixed(1)},${pt.y.toFixed(1)})`);
        return true;
      });
      if (!live.length) readout();
      raf = live.length ? requestAnimationFrame(frame) : null;
    }
    function reset() {
      i = 0; live.forEach((p) => p.node.remove()); live = [];
      Object.values(edges).forEach((e) => { e.n = 0; e.sum = 0; e.path.setAttribute("class", "d-edge"); e.path.style.strokeWidth = ""; });
      labels.forEach((l) => { l.sent = 0; l.got = 0; if (l.c) l.c.textContent = ""; });
      Object.values(pairs).forEach((p) => { p.n = 0; p.sum = 0; p.tone.textContent = ""; });
      ticks.forEach((t) => t.setAttribute("class", "d-tick"));
      log.replaceChildren(); readout();
    }
    function finish() { // the end state, without animation
      reset(); E.messages.forEach((m, idx) => { land(m); mark(idx); }); E.messages.slice(-3).forEach(logLine); i = E.messages.length; readout();
    }
    function run(on) {
      clearInterval(timer); timer = null;
      if (on && i < E.messages.length) timer = setInterval(send, E.seeded.length ? 900 : 260);
    }
    function restart() { reset(); run(ctl.on); }
    again.addEventListener("click", () => { reset(); ctl.set(true); });
    pick.addEventListener("change", () => { setup(+pick.value); if (reduce) finish(); else run(ctl.on); });
    // open on the friend-group triad; the others are in the picker
    const first = Math.max(0, exps.findIndex((e) => e.id === "friendship_trio_balanced"));
    pick.value = first;
    setup(first);
    const ctl = playable(root, run, btn, ["[ PLAY ]", "[ PAUSE ]"]);
    if (reduce) finish();
  });

  // ---------------------------------------------------------------- the invented language
  mount("words", (root) => {
    const { colors, shapes, sizes, objects, words } = DATA.words;
    const HEX = { red: "#e53935", blue: "#1e63d0", green: "#2e9e44", yellow: "#f2c300", purple: "#8e44ad", orange: "#f57c00", pink: "#ec6fa5", brown: "#7a4a21" };
    const SCALE = [0.38, 0.58, 0.79, 1];
    const index = {};
    objects.forEach((o, k) => { index[o.join(",")] = k; });

    // letters for the byte values the sender actually uses, most frequent first
    const freq = {};
    words.forEach((w) => w.forEach((b) => { freq[b] = (freq[b] || 0) + 1; }));
    const glyphs = "ABCDEFGHIJKLMNOPQRSTUVWXYZΔΣΦΨΩΓΛΞΠΘ".split("");
    const letter = {};
    Object.keys(freq).sort((a, b) => freq[b] - freq[a]).forEach((b, k) => { letter[b] = glyphs[k] || "?"; });

    function shapePath(name, r) {
      const poly = (pts) => "M" + pts.map((p) => p.map((v) => (v * r).toFixed(1)).join(",")).join("L") + "Z";
      const ring = (n, rot, inner) => {
        const pts = [];
        for (let k = 0; k < n * (inner ? 2 : 1); k++) {
          const rad = inner && k % 2 ? inner : 1;
          const a = rot + (Math.PI * 2 * k) / (n * (inner ? 2 : 1));
          pts.push([Math.cos(a) * rad, Math.sin(a) * rad]);
        }
        return poly(pts);
      };
      switch (name) {
        case "circle": return `M${-r},0a${r},${r} 0 1,0 ${2 * r},0a${r},${r} 0 1,0 ${-2 * r},0Z`;
        case "square": return poly([[-0.85, -0.85], [0.85, -0.85], [0.85, 0.85], [-0.85, 0.85]]);
        case "triangle": return ring(3, -Math.PI / 2);
        case "star": return ring(5, -Math.PI / 2, 0.42);
        case "cross": return poly([[-0.3, -1], [0.3, -1], [0.3, -0.3], [1, -0.3], [1, 0.3], [0.3, 0.3], [0.3, 1], [-0.3, 1], [-0.3, 0.3], [-1, 0.3], [-1, -0.3], [-0.3, -0.3]]);
        case "diamond": return poly([[0, -1], [0.7, 0], [0, 1], [-0.7, 0]]);
        case "hexagon": return ring(6, 0);
        default: return poly([[-1, -0.3], [0.2, -0.3], [0.2, -0.8], [1, 0], [0.2, 0.8], [0.2, 0.3], [-1, 0.3]]); // arrow
      }
    }
    function drawObject(o, box) {
      const s = svgEl(null, "svg", { viewBox: `${-box} ${-box} ${box * 2} ${box * 2}`, class: "w-obj", role: "img", "aria-label": `${sizes[o[2]]} ${colors[o[0]]} ${shapes[o[1]]}` });
      svgEl(s, "path", { d: shapePath(shapes[o[1]], box * 0.82 * SCALE[o[2]]), fill: HEX[colors[o[0]]] });
      return s;
    }

    root.append(html("p", { class: "viz-explain", text: "Two neural networks play a guessing game. The sender sees one object and may send only 8 symbols. The receiver must then pick that object out of a line-up of 8. Nobody gave them a language. This is the one they invented." }));
    const pickers = [["Colour", colors], ["Shape", shapes], ["Size", sizes]].map(([name, opts]) => {
      const sel = html("select", { "aria-label": name });
      opts.forEach((o, k) => sel.append(html("option", { value: k, text: o })));
      return sel;
    });
    const surprise = html("button", { class: "win-btn", type: "button", text: "Surprise me" });
    root.append(html("div", { class: "w-pick" },
      html("label", {}, "Colour ", pickers[0]), html("label", {}, "Shape ", pickers[1]), html("label", {}, "Size ", pickers[2]), surprise));
    const objBox = html("div", { class: "w-target" });
    const wordBox = html("div", { class: "w-word", "aria-live": "polite" });
    root.append(html("div", { class: "w-stage" }, objBox, html("div", {}, html("span", { class: "w-says", text: "the sender says:" }), wordBox)));
    const lineup = html("div", { class: "w-lineup" });
    root.append(html("p", { class: "w-label", text: "The receiver has to find it in a line-up like this (the target is ringed):" }), lineup);
    const note = html("p", { class: "viz-note" });
    root.append(note);

    let cur = [0, 3, 3], prevWord = null;
    function show(o, announce) {
      cur = o.slice();
      pickers.forEach((p, k) => { p.value = o[k]; });
      const k = index[o.join(",")];
      const word = words[k];
      objBox.replaceChildren(drawObject(o, 50), html("span", { text: `${sizes[o[2]]} ${colors[o[0]]} ${shapes[o[1]]}` }));
      wordBox.replaceChildren();
      let changed = 0;
      word.forEach((b, pos) => {
        const diff = prevWord && prevWord[pos] !== b;
        if (diff) changed++;
        wordBox.append(html("span", { class: "w-tile" + (diff ? " changed" : ""), text: letter[b] }));
      });
      note.textContent = prevWord && announce
        ? `${changed} of 8 symbols changed. A tidy language would change only the symbols for the feature you changed; this one mixes them (its tidiness score, topographic similarity, is 0.23, where 1 is perfectly tidy), yet the receiver still understands it.`
        : "Letters stand for the 31 byte values the sender actually uses. Change one feature and see which symbols change.";
      prevWord = word;
      // an example line-up: the target and 7 other objects
      let seed = k * 7919 + 13;
      const rnd = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff; };
      const others = new Set();
      while (others.size < 7) { const j = Math.floor(rnd() * objects.length); if (j !== k) others.add(j); }
      const row = [...others]; row.splice(Math.floor(rnd() * 8), 0, k);
      lineup.replaceChildren(...row.map((j) => html("span", { class: j === k ? "w-cand target" : "w-cand" }, drawObject(objects[j], 22))));
    }
    let auto = null, step = 0, touched = false;
    function demo() { // change one feature at a time so the differences are visible
      const o = cur.slice(), which = step++ % 3;
      const n = [colors.length, shapes.length, sizes.length][which];
      o[which] = (o[which] + 1 + Math.floor(Math.random() * (n - 1))) % n;
      show(o, true);
    }
    const stopDemo = () => { touched = true; clearInterval(auto); auto = null; };
    pickers.forEach((p) => p.addEventListener("change", () => { stopDemo(); show(pickers.map((q) => +q.value), true); }));
    surprise.addEventListener("click", () => { stopDemo(); show(objects[Math.floor(Math.random() * objects.length)], true); });
    show(cur, false);
    playable(root, (on) => {
      clearInterval(auto); auto = null;
      if (on && !touched) auto = setInterval(demo, 2600);
    });
  });

  // ---------------------------------------------------------------- the strip chart
  mount("strip", (root) => {
    const T = DATA.traces;
    const W = 360, PH = 86, L = 8, R = 352;
    const span = Math.max(T.moving.seconds, T.sleeping.seconds);
    const x = (sec) => L + (sec / span) * (R - L);
    const AX = [["x", "c1"], ["y", "c2"], ["z", "c3"]];

    root.append(html("p", { class: "viz-explain", text: "A motion sensor records acceleration 50 times a second in three directions. Walking shakes it in a fast rhythm. Sleep is almost flat, except when the sleeper rolls over. The models read one second at a time and say which it is." }));
    const svg = svgEl(null, "svg", { class: "strip-svg", viewBox: `0 0 ${W} 232`, role: "img", "aria-label": "Chart recorder drawing accelerometer traces for a walking recording and a sleeping recording" });
    root.append(svg);
    const defs = svgEl(svg, "defs", {});
    const clip = svgEl(svgEl(defs, "clipPath", { id: "strip-clip" }), "rect", { x: 0, y: 0, width: 0, height: 232 });

    const panels = [["moving", "Walking", 18], ["sleeping", "Sleeping", 130]].map(([key, title, top]) => {
      const d = T[key], mid = top + PH / 2, n = d.x.length;
      svgEl(svg, "rect", { class: "s-paper", x: L, y: top, width: R - L, height: PH });
      for (let g = 1; g < 4; g++) svgEl(svg, "line", { class: "s-grid", x1: L, x2: R, y1: top + (g * PH) / 4, y2: top + (g * PH) / 4 });
      for (let s = 5; s < span; s += 5) svgEl(svg, "line", { class: "s-grid", x1: x(s), x2: x(s), y1: top, y2: top + PH });
      svgEl(svg, "text", { class: "s-title", x: L, y: top - 5 }, title);
      const g = svgEl(svg, "g", { "clip-path": "url(#strip-clip)" });
      AX.forEach(([axis, cls]) => {
        const pts = d[axis].map((v, i) => `${x((i / (n - 1)) * d.seconds).toFixed(1)},${(mid - v * 34).toFixed(1)}`).join(" ");
        svgEl(g, "polyline", { class: "s-line " + cls, points: pts });
      });
      const win = svgEl(svg, "rect", { class: "s-window", y: top, height: PH, width: x(1) - x(0) });
      return { d, win };
    });
    const pen = svgEl(svg, "line", { class: "s-pen", y1: 12, y2: 222 });
    svgEl(svg, "text", { class: "s-tick", x: L, y: 229 }, "0 s");
    svgEl(svg, "text", { class: "s-tick", x: R, y: 229, "text-anchor": "end" }, `${Math.round(span)} s`);

    const btn = html("button", { class: "viz-btn", type: "button" });
    root.append(html("div", { class: "viz-bar" }, btn,
      html("span", { class: "s-key" }, html("i", { class: "c1" }), "side to side ", html("i", { class: "c2" }), "front to back ", html("i", { class: "c3" }), "up and down "),
      html("span", { class: "s-key" }, html("i", { class: "win" }), "the 1 second the model reads")));

    const meters = html("div", { class: "s-meters" });
    [["Best classical model (kNN)", 93], ["Best deep model (1D CNN)", 82], ["Always guessing “sleeping”", 59]].forEach(([name, v]) => {
      meters.append(html("div", { class: "s-meter" }, html("span", { text: name }), html("b", { text: v + "%" }), html("i", {}, html("u", { style: `--v:${v}%` }))));
    });
    root.append(html("p", { class: "w-label", text: "How often each gets a window right, on recordings it never saw:" }), meters);

    let sec = 0, raf = null, last = 0;
    function place() {
      clip.setAttribute("width", x(sec));
      pen.setAttribute("x1", x(sec)); pen.setAttribute("x2", x(sec));
      panels.forEach((p) => {
        const s = Math.min(sec, p.d.seconds);
        p.win.setAttribute("x", Math.max(L, x(s) - (x(1) - x(0))));
      });
    }
    function frame(now) {
      sec += ((now - last) / 1000) * 3; last = now; // three times real speed
      if (sec > span + 1.5) sec = 0;
      place();
      raf = requestAnimationFrame(frame);
    }
    playable(root, (on) => {
      cancelAnimationFrame(raf); raf = null;
      if (on) { last = performance.now(); raf = requestAnimationFrame(frame); }
    }, btn, ["Run the recorder", "Pause"]);
    if (reduce) { sec = span; place(); }
  });

  // ---------------------------------------------------------------- the market
  // One logged run of the simulator: price and shares traded each round, the
  // average wealth of each kind of trader, and the totals that must not change.
  mount("ticker", (root) => {
    const M = DATA.market, T = M.ticks, n = T.length, K = M.kinds;
    const price = T.map((t) => t[0]), vol = T.map((t) => t[1]);
    const W = 360, L = 30, R = 318, PT = 10, PB = 120, VT = 132, VB = 166, H = 186;
    const lo = Math.floor(Math.min(M.start.price, ...price) / 5) * 5, hi = Math.ceil(Math.max(...price) / 5) * 5;
    const vmax = Math.max(...vol);
    const x = (i) => L + (i / (n - 1)) * (R - L), y = (p) => PT + ((hi - p) / (hi - lo)) * (PB - PT);
    // how much richer or poorer each kind is than a trader who kept its starting
    // cash and shares and never traded (so a rising price alone scores zero)
    const gain = (k, i) => (T[i][2 + k] / (K[k].cash0 + K[k].shares0 * price[i]) - 1) * 100;
    const order = K.map((_, k) => k).sort((a, b) => gain(b, n - 1) - gain(a, n - 1));
    let peak = 1;
    for (let i = 0; i < n; i++) for (let k = 0; k < K.length; k++) peak = Math.max(peak, Math.abs(gain(k, i)));

    root.append(html("p", { class: "viz-explain", text: `${M.traders} robot traders, each following one simple rule, buy and sell a single made-up stock. Nobody sets the price: it is whatever the latest trades went for. Watch ${n} rounds, and see which rule makes money.` }));
    const read = html("p", { class: "viz-read tick-read", "aria-live": "off" });
    root.append(read);
    const svg = svgEl(null, "svg", { class: "tick-svg", viewBox: `0 0 ${W} ${H}`, role: "img", "aria-label": "The stock price and the number of shares traded, round by round" });
    root.append(svg);
    for (let v = lo; v <= hi; v += 5) {
      svgEl(svg, "line", { class: "t-grid", x1: L, x2: R, y1: y(v), y2: y(v) });
      svgEl(svg, "text", { class: "t-axis", x: L - 6, y: y(v) + 5, "text-anchor": "end" }, v);
    }
    svgEl(svg, "text", { class: "t-axis", x: R + 6, y: VB, "text-anchor": "start" }, "traded");
    svgEl(svg, "line", { class: "t-grid", x1: L, x2: R, y1: VB, y2: VB });
    [0, 100, 200, 300].forEach((v) => svgEl(svg, "text", { class: "t-axis", x: x(Math.min(v, n - 1)), y: H - 4, "text-anchor": "middle" }, v));
    const bw = Math.max(0.6, (R - L) / n - 0.3);
    const bars = vol.map((v, i) => svgEl(svg, "rect", { class: "t-vol", x: x(i) - bw / 2, width: bw, y: VB - (v / vmax) * (VB - VT), height: (v / vmax) * (VB - VT) }));
    svgEl(svg, "path", { class: "t-ghost", d: "M" + price.map((p, i) => `${x(i).toFixed(1)},${y(p).toFixed(1)}`).join("L") });
    const line = svgEl(svg, "path", { class: "t-line" });
    const head = svgEl(svg, "circle", { class: "t-head", r: 4 });
    const tag = svgEl(svg, "text", { class: "t-tag" });

    const btn = html("button", { class: "viz-btn", type: "button" });
    const scrub = html("input", { type: "range", min: 0, max: n - 1, value: 0, "aria-label": "Round of trading" });
    root.append(html("div", { class: "viz-bar" }, btn, scrub));

    root.append(html("p", { class: "viz-read board-head", text: "WHO BEAT DOING NOTHING? AVERAGE WEALTH BY KIND OF TRADER, AGAINST ONE WHO NEVER TRADED:" }));
    const board = html("div", { class: "board" });
    const rows = order.map((k) => {
      const bar = html("span", { class: "b-bar" }), pct = html("span", { class: "b-pct" });
      board.append(html("div", { class: "b-row", title: K[k].rule }, html("span", { class: "b-name", text: `${K[k].label} ×${K[k].n}` }), bar, pct));
      return { k, bar, pct };
    });
    root.append(board);

    // The written results go in the text column, so the chart and scoreboard
    // can stay in view while they are read.
    const card = root.closest("article");
    const out = (card && card.querySelector('[data-results="ticker"]')) || root;
    const section = (title, ...kids) => out.append(html("h4", { class: "r-head", text: title }), ...kids);
    const para = (text) => html("p", { class: "r-text", text });

    const rules = html("ul", { class: "r-rules" });
    order.forEach((k) => rules.append(html("li", {}, html("b", { text: `${K[k].label.charAt(0) + K[k].label.slice(1).toLowerCase()} (${K[k].n})` }), " " + K[k].rule)));
    section("The seven rules", rules);

    // why the ranking comes out this way: the price each kind of trader got
    const Y = M.why, coin = K.find((k) => k.id === "Py_Random");
    const stake = coin.cash0 + coin.shares0 * M.start.price;
    const side = (v, goodIfBelow) => {
      if (v == null) return html("span", { class: "y-cell", text: "never" });
      const below = v < 0, txt = v === 0 ? "same price" : `${Math.abs(v).toFixed(1)}% ${below ? "below" : "above"}`;
      return html("span", { class: "y-cell" + (v !== 0 && below !== goodIfBelow ? " loss" : ""), text: txt });
    };
    section("Why does the coin flip win?", para(
      `Not by choosing well. It wins on the price it gets. A coin-flip trader only ever says “buy now” or “sell now” at any price, so the exchange pairs it with the best offer on the other side. The random-orders traders supply those offers: they name prices up to 20% above or 10% below the going price without looking. In this run the coin flippers sold them ${Y.coin_sold_to_random.shares.toLocaleString("en-US")} shares at ${Y.coin_sold_to_random.vs.toFixed(1)}% above the going price and bought ${Y.coin_bought_from_random.shares.toLocaleString("en-US")} from them at ${Math.abs(Y.coin_bought_from_random.vs).toFixed(1)}% below. A small edge, taken every round for ${n} rounds, came to $${Math.round(coin.edge_each)} per coin-flip trader on a $${Math.round(stake)} stake.`));
    const why = html("div", { class: "why-table" });
    why.append(html("div", { class: "y-row y-head" }, html("span", {}), html("span", { class: "y-cell", text: "bought at" }), html("span", { class: "y-cell", text: "sold at" })));
    order.forEach((k) => why.append(html("div", { class: "y-row" }, html("span", { text: K[k].label.charAt(0) + K[k].label.slice(1).toLowerCase() }), side(K[k].buy_vs, true), side(K[k].sell_vs, false))));
    section("The price each kind got, against the going price", why, para(
      "Always buys has no such edge: it spent all its cash on shares in the first rounds, at about $10, and rode the price up. High bidder keeps offering $40 for shares worth far less. The simulator isn't seeded, so the numbers change from run to run, but in a second run the coin flip again came first and random orders last."));

    // why the neural network doesn't win: it gets no price edge, barely trades,
    // and the price has almost no pattern to learn
    const nn = K.find((k) => k.id === "LiveNN_trader"), nnIdx = K.indexOf(nn);
    const change = price.map((v, k) => v - (k ? price[k - 1] : M.start.price)).slice(1);
    const avg = change.reduce((t, v) => t + v, 0) / change.length;
    let num = 0, den = 0;
    change.forEach((v, k) => { den += (v - avg) * (v - avg); if (k) num += (v - avg) * (change[k - 1] - avg); });
    const signed = (v) => (v >= 0 ? "+" : "−") + Math.abs(v).toFixed(1) + "%";
    const perCoin = Math.round((coin.bought + coin.sold) / coin.n / 10) * 10;
    section("Why doesn’t the neural network win?", para(
      `This market doesn’t reward prediction. The winners profit from the prices they get, and the neural network’s one-share orders were filled at ${nn.buy_vs === 0 && nn.sell_vs === 0 ? "exactly the going price" : "close to the going price"}. It also barely trades: it spends the first ${M.nn.wait_rounds} of ${n} rounds collecting training data, then trades one share at a time, ${nn.bought + nn.sold} shares in all against about ${perCoin.toLocaleString("en-US")} for each coin-flip trader. And there is little to predict: with mostly random traders, one round’s price change is almost unrelated to the last (correlation ${(num / den).toFixed(2)}), and it learns from only ${M.nn.train_examples} examples. Its result is noise around zero: ${signed(gain(nnIdx, n - 1))} in this run, ${signed(M.other_run.nn)} in another.`));
    section("Audit", para(
      `${M.audit.shares.toLocaleString("en-US")} shares and $${M.audit.cash.toLocaleString("en-US")} in cash exist before the first round and after every one of the ${n}. Trading only moves them between traders, so the winners’ gains are exactly the losers’ losses.`));

    let i = 0, timer = null;
    function place() {
      let d = "";
      for (let k = 0; k <= i; k++) d += (k ? "L" : "M") + x(k).toFixed(1) + "," + y(price[k]).toFixed(1);
      line.setAttribute("d", d);
      head.setAttribute("cx", x(i)); head.setAttribute("cy", y(price[i]));
      tag.setAttribute("x", Math.min(x(i) + 8, W - 2)); tag.setAttribute("y", y(price[i]) + 5);
      tag.textContent = price[i].toFixed(1);
      bars.forEach((b, k) => b.classList.toggle("on", k <= i));
      const ch = price[i] - (i ? price[i - 1] : M.start.price);
      read.textContent = `ROUND ${String(i + 1).padStart(3, "0")}  PRICE ${price[i].toFixed(2)} ${ch >= 0 ? "▲" : "▼"}${Math.abs(ch).toFixed(2)}  TRADED ${vol[i]} SHARES`;
      rows.forEach((r) => {
        const g = gain(r.k, i), blocks = Math.round((Math.abs(g) / peak) * 12);
        r.bar.textContent = (g < 0 ? "▒" : "█").repeat(blocks);
        r.bar.className = g < 0 ? "b-bar loss" : "b-bar";
        r.pct.textContent = (g >= 0 ? "+" : "−") + Math.abs(g).toFixed(1) + "%";
        r.pct.className = g < 0 ? "b-pct loss" : "b-pct";
      });
      scrub.value = i;
    }
    function tick() { i = i >= n - 1 ? 0 : i + 1; place(); }
    const ctl = playable(root, (on) => { clearInterval(timer); timer = null; if (on) timer = setInterval(tick, 90); }, btn, ["[ PLAY ]", "[ PAUSE ]"]);
    scrub.addEventListener("input", () => { ctl.set(false); i = +scrub.value; place(); });
    if (reduce) i = n - 1;
    place();
  });

  // ---------------------------------------------------------------- particle life
  // A browser port of the rules in Particle_Simulator/Clusters/clusters.c:
  // random attraction or repulsion per pair of types with a Gaussian profile,
  // push-apart on overlap, friction, a wrap-around world and a 50 px grid.
  mount("particles", (root) => {
    const SIZE = 700, TYPES = 8, PER = 100, N = TYPES * PER, CELL = 50, COLS = SIZE / CELL;
    const MIN_D = 3, MAX_D = 50, FRICTION = 0.8, GRAVITY = 0.05, MAX_SPEED = 60;
    const COLORS = ["#5577ff", "#ff5555", "#55ff55", "#ffff55", "#ff55ff", "#55ffff", "#ffffff", "#ffaa00"];

    root.append(html("p", { class: "viz-explain", text: "Each dot has one of 8 colours. Every pair of colours either attracts or repels, by rules picked at random. That is the whole program, yet the dots gather into clusters that drift around like living cells. Press New rules for a different world." }));
    const canvas = html("canvas", { width: SIZE, height: SIZE, class: "p-canvas", role: "img", "aria-label": "Live particle simulation: 800 coloured dots forming clusters" });
    root.append(html("div", { class: "win-sunken p-screen" }, canvas));
    const btn = html("button", { class: "win-btn", type: "button" });
    const fresh = html("button", { class: "win-btn", type: "button", text: "New rules" });
    root.append(html("div", { class: "viz-bar" }, fresh, btn));
    root.append(html("p", { class: "viz-note", text: "Running live in your browser with the simulator's rules. The original is written in C and splits the work across CPU cores with OpenMP." }));
    const ctx = canvas.getContext("2d");

    const px = new Float32Array(N), py = new Float32Array(N), vx = new Float32Array(N), vy = new Float32Array(N);
    const sx = new Float32Array(N), sy = new Float32Array(N), type = new Uint8Array(N);
    const force = new Float32Array(TYPES * TYPES), reach = new Float32Array(TYPES * TYPES);
    const cellStart = new Int32Array(COLS * COLS + 1), cellOf = new Int32Array(N), order = new Int32Array(N);

    function rules() {
      for (let k = 0; k < TYPES * TYPES; k++) {
        force[k] = Math.random() * 2 - 1;                                   // MIN_FORCE..MAX_FORCE
        reach[k] = MIN_D + Math.floor(Math.random() * (MAX_D - MIN_D + 1)); // MIN_COL_DIST..MAX_COL_DIST
      }
    }
    function scatter() {
      for (let i = 0; i < N; i++) { px[i] = Math.random() * SIZE; py[i] = Math.random() * SIZE; vx[i] = vy[i] = 0; type[i] = Math.floor(i / PER); }
    }
    function step() {
      // counting sort into grid cells, as assign_balls_to_grid does
      cellStart.fill(0);
      for (let i = 0; i < N; i++) {
        const c = (Math.floor(py[i] / CELL) % COLS + COLS) % COLS * COLS + (Math.floor(px[i] / CELL) % COLS + COLS) % COLS;
        cellOf[i] = c; cellStart[c + 1]++;
      }
      for (let c = 0; c < COLS * COLS; c++) cellStart[c + 1] += cellStart[c];
      const fill = cellStart.slice(0, COLS * COLS);
      for (let i = 0; i < N; i++) order[fill[cellOf[i]]++] = i;
      sx.set(px); sy.set(py); // forces read the positions from the start of the frame

      for (let i = 0; i < N; i++) {
        const ci = cellOf[i], row = Math.floor(ci / COLS), col = ci % COLS, ti = type[i] * TYPES;
        for (let dr = -1; dr <= 1; dr++) for (let dc = -1; dc <= 1; dc++) {
          const c = ((row + dr + COLS) % COLS) * COLS + ((col + dc + COLS) % COLS);
          for (let q = cellStart[c]; q < cellStart[c + 1]; q++) {
            const j = order[q];
            if (j === i) continue;
            let dx = sx[j] - px[i], dy = sy[j] - py[i];
            if (dx > SIZE / 2) dx -= SIZE; else if (dx < -SIZE / 2) dx += SIZE;
            if (dy > SIZE / 2) dy -= SIZE; else if (dy < -SIZE / 2) dy += SIZE;
            const d2 = dx * dx + dy * dy;
            if (d2 < 1e-6) continue;
            const max = reach[ti + type[j]];
            if (d2 > max * max) continue;
            const d = Math.sqrt(d2);
            if (d < 2 * MIN_D) { // overlapping: push this one away
              const overlap = (2 * MIN_D - d) / 2;
              px[i] -= dx * (overlap / d); py[i] -= dy * (overlap / d);
              if (px[i] < 0) px[i] += SIZE; else if (px[i] >= SIZE) px[i] -= SIZE;
              if (py[i] < 0) py[i] += SIZE; else if (py[i] >= SIZE) py[i] -= SIZE;
            }
            if (d < MIN_D) continue;
            const ideal = max / 2, sigma = ideal / 3;
            const f = force[ti + type[j]] * Math.exp(-((d - ideal) * (d - ideal)) / (2 * sigma * sigma));
            vx[i] += (dx / d) * f; vy[i] += (dy / d) * f;
          }
        }
      }
      for (let i = 0; i < N; i++) {
        vx[i] *= FRICTION; vy[i] *= FRICTION; py[i] += GRAVITY;
        const s2 = vx[i] * vx[i] + vy[i] * vy[i];
        if (s2 > MAX_SPEED * MAX_SPEED) { const s = Math.sqrt(s2); vx[i] = (vx[i] / s) * MAX_SPEED; vy[i] = (vy[i] / s) * MAX_SPEED; }
        px[i] += vx[i]; py[i] += vy[i];
        if (px[i] >= SIZE) px[i] -= SIZE; else if (px[i] < 0) px[i] += SIZE;
        if (py[i] >= SIZE) py[i] -= SIZE; else if (py[i] < 0) py[i] += SIZE;
      }
    }
    function draw() {
      ctx.fillStyle = "#000"; ctx.fillRect(0, 0, SIZE, SIZE);
      for (let t = 0; t < TYPES; t++) {
        ctx.fillStyle = COLORS[t];
        for (let i = t * PER; i < (t + 1) * PER; i++) ctx.fillRect(px[i] - 2.5, py[i] - 2.5, 5, 5);
      }
    }
    let raf = null, last = 0;
    function frame(now) {
      if (now - last >= 33) { last = now; step(); draw(); } // the original runs at 30 frames a second
      raf = requestAnimationFrame(frame);
    }
    rules(); scatter();
    for (let k = 0; k < (reduce ? 300 : 40); k++) step();
    draw();
    fresh.addEventListener("click", () => { rules(); scatter(); draw(); });
    playable(root, (on) => { cancelAnimationFrame(raf); raf = null; if (on) raf = requestAnimationFrame(frame); }, btn, ["Play", "Pause"]);
  });

  // ---------------------------------------------------------------- SVD slider
  mount("svd", (root) => {
    const ranks = DATA.svd.ranks;
    root.append(html("p", { class: "viz-explain", text: "A picture is a grid of numbers. SVD sorts the picture's patterns from most to least important. Keep only the top few and you can rebuild it from a fraction of the data. Drag the slider." }));
    const img = html("img", { class: "svd-img", width: 480, height: 271, alt: "" });
    root.append(img);
    const slider = html("input", { type: "range", min: 0, max: ranks.length - 1, value: 0, "aria-label": "How many patterns to keep" });
    const read = html("p", { class: "svd-read", "aria-live": "polite" });
    root.append(html("div", { class: "svd-ctl" }, html("span", { text: "less data" }), slider, html("span", { text: "more data" })), read);
    ranks.forEach((r) => { new Image().src = `img/svd-${r.rank}.webp`; });
    function show(k) {
      const r = ranks[k];
      slider.value = k;
      img.src = `img/svd-${r.rank}.webp`;
      img.alt = `The image rebuilt from its top ${r.rank} patterns`;
      const pct = r.share * 100;
      read.replaceChildren(html("b", { text: r.rank === 1 ? "1 pattern" : `${r.rank} patterns` }),
        r.share >= 1 ? " kept: the original image, every number." : ` kept: rebuilt from ${pct < 10 ? pct.toFixed(1) : Math.round(pct)}% of the numbers.`);
    }
    let auto = null, k = 0, touched = false;
    slider.addEventListener("input", () => { touched = true; clearInterval(auto); auto = null; show(+slider.value); });
    show(reduce ? 8 : 0);
    playable(root, (on) => {
      clearInterval(auto); auto = null;
      if (on && !touched) auto = setInterval(() => { k = (k + 1) % ranks.length; show(k); }, 900);
    });
  });

  // ---------------------------------------------------------------- page-level life
  // Windows open in their era's way the first time they scroll into view.
  if (!reduce) {
    const opener = new IntersectionObserver((entries) => {
      entries.forEach((e) => { if (e.isIntersecting) { e.target.classList.add("open"); opener.unobserve(e.target); } });
    }, { threshold: 0.08 });
    document.querySelectorAll(".mac, .term, .win, .manual").forEach((w) => { w.classList.add("pre"); opener.observe(w); });
  }
  // Beside a tall column, the shorter one stays in view while you scroll,
  // provided it fits on screen.
  const projs = Array.from(document.querySelectorAll(".proj"));
  let balancing = 0;
  function balance() {
    balancing = 0;
    const wide = window.matchMedia("(min-width: 961px)").matches;
    projs.forEach((p) => {
      const kids = Array.from(p.children);
      if (kids.length !== 2) return;
      const short = kids[0].offsetHeight <= kids[1].offsetHeight ? kids[0] : kids[1];
      const fits = wide && short.offsetHeight <= window.innerHeight - 70;
      kids.forEach((k) => k.classList.toggle("stick", fits && k === short));
    });
  }
  const queue = () => { if (!balancing) balancing = requestAnimationFrame(balance); };
  window.addEventListener("resize", queue);
  if (window.ResizeObserver) {
    const ro = new ResizeObserver(queue);
    projs.forEach((p) => Array.from(p.children).forEach((k) => ro.observe(k)));
  }
  balance();

  const clock = document.getElementById("clock");
  if (clock) {
    const tick = () => { clock.textContent = new Date().toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); };
    tick(); setInterval(tick, 20000);
  }
})();
